// Generated by Selenium IDE

import com.minhw.utils.ExcelUtils;
import org.junit.After;
import org.junit.Test;
import org.junit.Before;

import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.chrome.ChromeOptions;

import java.time.Duration;
import java.util.*;

public class XinshangmengTest {
    private WebDriver driver;
    private Map<String, Object> vars;

    //    private Map<String, String> excel;
    /**
     * excel文件的路径
     * https://web.baimiaoapp.com/image-to-excel 图片转excel
     */
    String path = "/Users/minhongwei/Desktop/第33期公示表.xlsx";
    /**
     * 新商盟登录用户名和密码。请自行修改
     */
    String username = "你的账号";
    String password = "你的密码";

    //        订购的数据sheet位于excel的那个位置，从0开始
    int sheetIndex = 1;
    JavascriptExecutor js;

    @Before
    public void setUp() {
//        excel = ExcelUtils.readExcel();

        ChromeOptions option = new ChromeOptions();
        option.addArguments("--remote-allow-origins=*");
        driver = new ChromeDriver(option);
        js = (JavascriptExecutor) driver;
        vars = new HashMap<String, Object>();
    }

    // @After
    // public void tearDown() {
    //     driver.quit();
    // }

    @Test
    public void login() {
        driver.get("http://www.xinshangmeng.com/");
        driver.manage().timeouts().implicitlyWait(Duration.ofSeconds(10));
        driver.findElement(By.id("username")).click();
        driver.findElement(By.id("username")).sendKeys(username);
        driver.findElement(By.id("mcmm1")).click();
        driver.findElement(By.id("mcmm1")).sendKeys(password);
        driver.findElement(By.id("btn-login")).click();

    }

    @Test
    public void xinshangmeng() throws InterruptedException {
        Map<String, String> excel = ExcelUtils.readExcel(path, sheetIndex);
        if (excel.size() < 1) {
            System.err.println("excel文件中没有数据");
            return;
        }
        // System.out.printf("%s, %s%n", excel.values(), excel.keySet());
        driver.get("http://www.xinshangmeng.com/");
        driver.manage().timeouts().implicitlyWait(Duration.ofSeconds(10));
        driver.findElement(By.id("username")).click();
        driver.findElement(By.id("username")).sendKeys(username);
        driver.findElement(By.id("mcmm1")).click();
        driver.findElement(By.id("mcmm1")).sendKeys(password);
        driver.findElement(By.id("btn-login")).click();

        driver.findElement(By.linkText("关闭")).click();

        driver.findElement(By.linkText("卷烟订货")).click();

//        By search = By.id("cgtIdNameSearch");
//        driver.findElement(search).click();
//        driver.findElement(search).sendKeys("0143");
//        driver.findElement(By.id("confirmm")).click();
//        System.out.printf(driver.findElement(By.cssSelector("#newul > li:nth-child(1)")).toString());
//        List<WebElement> elementList = driver.findElements(By.cssSelector("#newul li"));
        WebElement futureElement = driver.findElement(By.id("newul"));
        List<WebElement> elementList = futureElement.findElements(By.tagName("li"));
        // By.id("newul"));
        System.out.println("获取到可选订单列表数量：" + elementList.size());
        for (WebElement e : elementList) {
            // Thread.sleep(1000);
            System.out.println(e.getAttribute("title"));
            String title = e.getAttribute("title").trim()
                    .replace('（', '(')
                    .replace('）', ')');
            if (excel.get(title) != null) {
                System.out.println(e.getAttribute("data-cgt-code"));
                String req_id = "req_qty_" + e.getAttribute("data-cgt-code").trim();
                System.err.println("成功订购香烟，名:" + title + ", 订单数量: " + excel.get(title) + "。剩于定烟品种 " + (excel.size() - 1));
                By search = By.id("cgtIdNameSearch");
                driver.findElement(search).click();
                driver.findElement(search).sendKeys(title);
                driver.findElement(By.id("confirmm")).click();
                Thread.sleep(1000);
                driver.findElement(By.id(req_id)).click();
                Thread.sleep(1000);
//                driver.findElement(By.id(req_id)).clear();
//                Thread.sleep(1000);
                driver.findElement(By.id(req_id)).sendKeys(excel.get(title));
//                操作 完成删除对应值
                excel.remove(title);
                driver.findElement(search).clear();
            }

//            如果对应的值空了，说明订货完成，直接推出循环
            if (excel.size() < 1) {
                System.out.println("--------------------订货完成，退出循环-------------------");
                break;
            }
        }
        if (excel.size() > 0) {
            System.err.println("未订购的香烟有：" + excel.entrySet());
            // return;
        }
        Thread.sleep(1000);
        driver.findElement(By.id("accinfo")).click();
//        将得到的余额打印到控制台
        System.err.println("余额：" + driver.findElement(By.cssSelector("#accerror > span")).getText());
        Thread.sleep(1000);
        driver.findElement(By.id("smt")).click();
        Thread.sleep(1000);
        driver.findElement(By.id("subbtn")).click();
        Thread.sleep(3000);
        System.err.println("提交结果 " + driver.findElement(By.xpath("//*[@id=\"content\"]/div[2]/div[1]")).getText());

    }
}
